### ISSUE TITLE
Failed build-storybook commands

### ISSUE THREAD

**Issue by seonghyeonkimm** [chromaui/action#37] opened 2020-07-31 02:20 UTC
## Descriptions
- I want to use this action to deploy my storybook to chromatic
- However build failed with error like below
- Could I get help about this problem to resolve and complete upload storybook?
- On my local machine, `build-storybook` does not throw any errors.

```
  {
"timestamp": "2020-07-31T02:12:53.357Z",
"sessionId": "597648fd-3812-4618-b8b3-7e5d4e5d59b5",
"gitVersion": "2.27.0",
##[error]Cannot destructure property `webUrl` of 'undefined' or 'null'.
"nodePlatform": "linux",
##[error]TypeError: Cannot destructure property `webUrl` of 'undefined' or 'null'.
    at runChromatic (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:65:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async run (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:120:33)
"nodeVersion": "12.13.1",
##[error]Cannot destructure property `webUrl` of 'undefined' or 'null'.
"packageName": "chromatic",
"packageVersion": "5.0.0",
"storybook": {
  "version": "5.3.19",
  "viewLayer": "react",
  "addons": [
    {
      "name": "actions",
      "packageName": "@storybook/addon-actions",
      "packageVersion": "5.3.19"
    },
    {
      "name": "links",
      "packageName": "@storybook/addon-links",
      "packageVersion": "5.3.19"
    }
  ]
},
"flags": {
  "projectToken": "***",
  "fromCI": true,
  "interactive": false,
  "exitZeroOnChanges": true,
  "exitOnceUploaded": false,
  "allowConsoleErrors": false
},
"errorType": "Error",
"errorMessage": "✖ Failed to build Storybook\nCommand failed with exit code 1: npm run --silent build-storybook -- --output-dir /tmp/chromatic-2693nz3iqGPzbF9e"
}

```

```
Error: ✖ Failed to build Storybook
Command failed with exit code 1: npm run --silent build-storybook -- --output-dir /tmp/chromatic-2693nz3iqGPzbF9e
  at makeError (/home/runner/work/_actions/chromaui/action/v1/node_modules/execa/lib/error.js:59:11)
  at handlePromise (/home/runner/work/_actions/chromaui/action/v1/node_modules/execa/index.js:114:26)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async buildStorybook (/home/runner/work/_actions/chromaui/action/v1/node_modules/chromatic/bin/tasks/build.js:50:5)
  at async Task.task (/home/runner/work/_actions/chromaui/action/v1/node_modules/chromatic/bin/lib/tasks.js:13:7)
```

**Comment by cereallarceny** [comment] 2020-07-31 15:47
Duplicate of https://github.com/chromaui/action/issues/36

**Comment by seonghyeonkimm** [comment] 2020-08-04 01:00
I found out a workaround. First build and use this action.
For example like below.

```
      - run: npm run build-storybook
      - uses: chromaui/action@v1
        with: 
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: storybook-static
```

**Closed** 2020-08-04 01:01 UTC

**Comment by cereallarceny** [comment] 2020-08-04 09:30
When I did that it still doesn't work.
